version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    stdin_open: true  # Permite entrada estándar (necesario para terminal interactiva)
    tty: true          # Asigna una terminal pseudo-TTY
