"""
Module: raw_response

Defines the RawResponse model for handling AI-generated responses.

This module provides a Pydantic model to standardize and validate the structure
of responses generated by AI models. It includes fields for the generated text,
token counts, model name, and optional metadata.

Example:
    >>> from src.models import RawResponse
    >>> response = RawResponse(
    ...     generated_text="Hello, world!",
    ...     prompt_tokens=5,
    ...     response_tokens=10,
    ...     model_name="gemini-1.5-flash",
    ...     metadata={"temperature": 0.7}
    ... )
    >>> print(response.generated_text)

Dependencies:
    - pydantic
    - typing
"""

from pydantic import BaseModel
from typing import Optional, Any

class RawResponse(BaseModel):
    """
    Represents the structure of an AI-generated response.

    Attributes:
        generated_text (str): The text generated by the AI model.
        prompt_tokens (int): The number of tokens in the input prompt.
        response_tokens (int): The number of tokens in the generated response.
        model_name (str): The name of the model used for generation.
        metadata (Optional[Any]): Additional metadata about the response (e.g., temperature, top_p).
    """
    generated_text: str
    prompt_tokens: int
    response_tokens: int
    model_name: str
    metadata: Optional[Any] = None

    class Config:
        """
        Pydantic configuration for the RawResponse model.
        """
        from_attributes = True